// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMsMvh_q5NKXc_TxFF3RSLoSnzD6RqPKA',
    appId: '1:315217136213:web:e518e5c2ed4d0b0d1f22dc',
    messagingSenderId: '315217136213',
    projectId: 'flutterfirebaseauth2-84988',
    authDomain: 'flutterfirebaseauth2-84988.firebaseapp.com',
    storageBucket: 'flutterfirebaseauth2-84988.appspot.com',
    measurementId: 'G-XYQTXYKLG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjzJls1M9VN4976c4H2fjyhyvjRdwFaOo',
    appId: '1:315217136213:android:2da05261ede3424f1f22dc',
    messagingSenderId: '315217136213',
    projectId: 'flutterfirebaseauth2-84988',
    storageBucket: 'flutterfirebaseauth2-84988.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD21k9delzQTbgssoO3qup-CZrrQFjsJfg',
    appId: '1:315217136213:ios:eec5048f5b01a0411f22dc',
    messagingSenderId: '315217136213',
    projectId: 'flutterfirebaseauth2-84988',
    storageBucket: 'flutterfirebaseauth2-84988.appspot.com',
    iosClientId: '315217136213-ts6ga4n2apsjibnff80m6m4551cnjp8u.apps.googleusercontent.com',
    iosBundleId: 'com.exampl',
  );
}
