// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ZTHatk_DAsI91EeTMdn7Xc1tNJs0BPs',
    appId: '1:848293607347:web:d418e262f052dc72c1fdc6',
    messagingSenderId: '848293607347',
    projectId: 'flutter-push-notificatio-20177',
    authDomain: 'flutter-push-notificatio-20177.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-20177.appspot.com',
    measurementId: 'G-NBWCL3P154',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Uu8tgGVSucZZEn4d435IbxHIfwhkyqc',
    appId: '1:848293607347:android:c9f076c7dec76102c1fdc6',
    messagingSenderId: '848293607347',
    projectId: 'flutter-push-notificatio-20177',
    storageBucket: 'flutter-push-notificatio-20177.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALi0Zdi9jqsO8lXpUnxHyYKbuS_mDtCMk',
    appId: '1:848293607347:ios:ae2a3c6690f89c78c1fdc6',
    messagingSenderId: '848293607347',
    projectId: 'flutter-push-notificatio-20177',
    storageBucket: 'flutter-push-notificatio-20177.appspot.com',
    iosClientId: '848293607347-4o0r0in1s02q1bnhcqhlu4oit8vtkp0n.apps.googleusercontent.com',
    iosBundleId: 'com.ex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALi0Zdi9jqsO8lXpUnxHyYKbuS_mDtCMk',
    appId: '1:848293607347:ios:32c7282dd291c409c1fdc6',
    messagingSenderId: '848293607347',
    projectId: 'flutter-push-notificatio-20177',
    storageBucket: 'flutter-push-notificatio-20177.appspot.com',
    iosClientId: '848293607347-7qm9mtd4ka5btul2i9181ee0ffncjkvg.apps.googleusercontent.com',
    iosBundleId: 'com.',
  );
}
