// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsBuqKkcY17JGQri6NJzDJIInZBUup2Cw',
    appId: '1:1007935526654:web:05a385b69c0d386e2bf7af',
    messagingSenderId: '1007935526654',
    projectId: 'flutter-chat-app-4e60b',
    authDomain: 'flutter-chat-app-4e60b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4e60b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVqx-KkZ8eOC6-_MU4o2SGdnXO7N-ZeQ0',
    appId: '1:1007935526654:android:da7f01262a79e2062bf7af',
    messagingSenderId: '1007935526654',
    projectId: 'flutter-chat-app-4e60b',
    storageBucket: 'flutter-chat-app-4e60b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_bnTqMhrJsuEF61GNDP-xPg5BkMztiB0',
    appId: '1:1007935526654:ios:fd852befb78a7ccd2bf7af',
    messagingSenderId: '1007935526654',
    projectId: 'flutter-chat-app-4e60b',
    storageBucket: 'flutter-chat-app-4e60b.appspot.com',
    iosClientId: '1007935526654-cptvo6rlqk9dac07fijl1ngjr0s7gdcm.apps.googleusercontent.com',
    iosBundleId: 'com.exampl',
  );
}
