// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsg6Rph2nWX5kjf_DS2Rt1BfWZ00bgcJQ',
    appId: '1:651087106699:web:206dce1f1e14afe1763a8e',
    messagingSenderId: '651087106699',
    projectId: 'flutter-firebase-auth3',
    authDomain: 'flutter-firebase-auth3.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMIJ2ftPbp5HDldjssh1oRXOPKYu84imo',
    appId: '1:651087106699:android:8e4bf4b71c4a14cc763a8e',
    messagingSenderId: '651087106699',
    projectId: 'flutter-firebase-auth3',
    storageBucket: 'flutter-firebase-auth3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjG9uB2ed7jAmdm4OJU_2VgIvoevQTLI',
    appId: '1:651087106699:ios:502fab8231f08d49763a8e',
    messagingSenderId: '651087106699',
    projectId: 'flutter-firebase-auth3',
    storageBucket: 'flutter-firebase-auth3.appspot.com',
    iosClientId: '651087106699-apl588pmh61osgfsru2lese0jbpvogbg.apps.googleusercontent.com',
    iosBundleId: 'com.exampl',
  );
}
